apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: extreamer-incoming-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: extreamer-incoming
  minReplicas: 2
  maxReplicas: 12
  targetCPUUtilizationPercentage: 60
