service: ex-streamer-encoder
runtime: custom
resources:
  cpu: 2
  memory_gb: 2.3
env: flex

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 3600
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2